# Autostart configs
exec-once = waybar
exec-once = hypr-u
exec-once = hyprpaper
exec-once = systemctl --user start hyprpolkitagent
exec-once = dunst
exec-once = /usr/lib/pam_kwallet_init &
exec-once = syncthing -no-browser

# Windows on specifc workspaces

exec-once = [workspace 9 silent] keepassxc
exec-once = [workspace 8 silent] vesktop

# Special Workspaces
exec-once = [workspace special:mail silent] thunderbird

